import _ from 'lodash';
import { strict as assert } from 'assert';
import debugFactory from 'debug';
const debug = debugFactory('test:cancel');
import slugid from 'slugid';
import taskcluster from 'taskcluster-client';
import assume from 'assume';
import helper from './helper.js';
import testing from 'taskcluster-lib-testing';

helper.secrets.mockSuite(testing.suiteName(), ['aws'], function(mock, skipping) {
  helper.withDb(mock, skipping);
  helper.withAmazonIPRanges(mock, skipping);
  helper.withPulse(mock, skipping);
  helper.withS3(mock, skipping);
  helper.withServer(mock, skipping);
  helper.resetTables(mock, skipping);

  // Use the same task definition for everything
  const taskDef = {
    taskQueueId: 'no-provisioner-extended-extended/test-worker-extended-extended',
    schedulerId: 'my-scheduler-extended-extended',
    taskGroupId: 'dSlITZ4yQgmvxxAi4A8fHQ',
    routes: [],
    retries: 5,
    created: taskcluster.fromNowJSON(),
    deadline: taskcluster.fromNowJSON('3 days'),
    scopes: [],
    payload: {},
    metadata: {
      name: 'Unit testing task',
      description: 'Task created during unit tests',
      owner: 'jonsafj@mozilla.com',
      source: 'https://github.com/taskcluster/taskcluster-queue',
    },
    tags: {
      purpose: 'taskcluster-testing',
    },
  };

  test('createTask, cancelTask (idempotent)', async () => {
    const taskId = slugid.v4();

    debug('### Create task');
    const r1 = await helper.queue.createTask(taskId, taskDef);
    assume(r1.status.state).equals('pending');
    assume(r1.status.runs.length).equals(1);
    assume(r1.status.runs[0].state).equals('pending');
    helper.assertPulseMessage('task-defined');
    helper.assertPulseMessage('task-pending');

    debug('### Cancel Task');
    const r2 = await helper.queue.cancelTask(taskId);
    assume(r2.status.state).equals('exception');
    assume(r2.status.runs.length).equals(1);
    assume(r2.status.runs[0].state).equals('exception');
    assume(r2.status.runs[0].reasonCreated).equals('scheduled');
    assume(r2.status.runs[0].reasonResolved).equals('canceled');
    helper.assertPulseMessage('task-exception', m => _.isEqual(m.payload.status, r2.status));
    helper.clearPulseMessages();

    debug('### Cancel Task (again)');
    const r3 = await helper.queue.cancelTask(taskId);
    assume(r3.status).deep.equals(r2.status);
    helper.assertPulseMessage('task-exception', m => _.isEqual(m.payload.status, r2.status));
  });

  test('createTask (unscheduled), cancelTask (race)', async () => {
    const taskId = slugid.v4();

    debug('### Create unscheduled task');
    const r1 = await helper.queue.createTask(taskId, {
      ...taskDef,
      dependencies: [taskId],
    });
    assume(r1.status.state).equals('unscheduled');
    assume(r1.status.runs.length).equals(0);
    helper.assertPulseMessage('task-defined');

    debug('### Cancel Task 10x at once');
    // allSettled waits for all attempts to finish before returning
    const res = await Promise.allSettled(_.range(10).map(async () => {
      const r2 = await helper.queue.cancelTask(taskId);
      assume(r2.status.state).equals('exception');
      assume(r2.status.runs.length).equals(1);
      assume(r2.status.runs[0].state).equals('exception');
      assume(r2.status.runs[0].reasonCreated).equals('exception');
      assume(r2.status.runs[0].reasonResolved).equals('canceled');
    }));
    // raise any exceptions in any of those calls
    for (let { reason } of res) {
      if (reason) {
        throw reason;
      }
    }
    helper.assertPulseMessage('task-exception');
    helper.clearPulseMessages();
  });

  test('createTask (scheduled), cancelTask (race)', async () => {
    const taskId = slugid.v4();

    debug('### Create unscheduled task');
    const r1 = await helper.queue.createTask(taskId, taskDef);
    assume(r1.status.state).equals('pending');
    assume(r1.status.runs.length).equals(1);
    helper.assertPulseMessage('task-defined');
    helper.assertPulseMessage('task-pending');

    debug('### Cancel Task 10x at once');
    // allSettled waits for all attempts to finish before returning
    const res = await Promise.allSettled(_.range(10).map(async () => {
      const r2 = await helper.queue.cancelTask(taskId);
      assume(r2.status.state).equals('exception');
      assume(r2.status.runs.length).equals(1);
      assume(r2.status.runs[0].state).equals('exception');
      assume(r2.status.runs[0].reasonCreated).equals('scheduled');
      assume(r2.status.runs[0].reasonResolved).equals('canceled');
    }));
    // raise any exceptions in any of those calls
    for (let { reason } of res) {
      if (reason) {
        throw reason;
      }
    }
    //helper.assertPulseMessage('task-exception', m => _.isEqual(m.payload.status, r2.status));
    helper.clearPulseMessages();
  });

  test('cancelTask with project-related scopes', async () => {
    const taskId = slugid.v4();

    debug('### Create unscheduled task');
    await helper.queue.createTask(taskId, {
      ...taskDef,
      projectId: 'testproj',
    });

    helper.scopes('queue:cancel-task-in-project:testproj');
    const r2 = await helper.queue.cancelTask(taskId);
    assume(r2.status.state).equals('exception');

    // fails with the wrong project scope
    helper.scopes('queue:cancel-task-in-project:WRONG-PROJECT');
    await assert.rejects(
      () => helper.queue.cancelTask(taskId),
      err => err.statusCode === 403);

    helper.clearPulseMessages();
  });

  test('createTask, claimTask, cancelTask (idempotent)', async () => {
    const taskId = slugid.v4();

    debug('### Create task');
    const r1 = await helper.queue.createTask(taskId, taskDef);
    assume(r1.status.state).equals('pending');
    assume(r1.status.runs.length).equals(1);
    assume(r1.status.runs[0].state).equals('pending');
    helper.assertPulseMessage('task-defined');
    helper.assertPulseMessage('task-pending');

    debug('### Claim task');
    const r2 = await helper.queue.claimTask(taskId, 0, {
      workerGroup: 'my-worker-group-extended-extended',
      workerId: 'my-worker-extended-extended',
    });
    assume(r2.status.state).equals('running');
    helper.assertPulseMessage('task-running');

    debug('### Cancel Task');
    const r3 = await helper.queue.cancelTask(taskId);
    assume(r3.status.state).equals('exception');
    assume(r3.status.runs.length).equals(1);
    assume(r3.status.runs[0].state).equals('exception');
    assume(r3.status.runs[0].reasonCreated).equals('scheduled');
    assume(r3.status.runs[0].reasonResolved).equals('canceled');
    helper.assertPulseMessage('task-exception', m => _.isEqual(m.payload.status, r3.status));
    helper.clearPulseMessages();

    debug('### Cancel Task (again)');
    const r4 = await helper.queue.cancelTask(taskId);
    assume(r4.status).deep.equals(r3.status);
    helper.assertPulseMessage('task-exception', m => _.isEqual(m.payload.status, r3.status));
  });
});
